# Workflow for CI tests
name: CI-documentation-and-format

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request: # All PRs
  #  branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: BICEPS

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-formatting:
    # Skip if the commit message contains "ci skip"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-18.04

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: "Install pip"
        run: pip3 install --upgrade pip wheel

      - name: "Install BuildingsPy"
        run: pip3 install git+https://github.com/lbl-srg/BuildingsPy@1b4308545bc793718c2c7b5b25a3f0f9df12588e

      - name: "Test html syntax"
        run : python ../bin/runUnitTests.py --validate-html-only

      - name: "Test experiment setup"
        run : python ../bin/runUnitTests.py --validate-experiment-setup

      - name: "Test if package.order are correct"
        run : |
              python -c 'import buildingspy.development.refactor as r; r.write_package_order(".", recursive=True)'
              git diff --exit-code .
     
      - name: "Verify files for invalid strings"
        run: python ${GITHUB_WORKSPACE}/bin/verifyFiles.py

